### ISSUE TITLE
OpenEXR

### ISSUE THREAD

**Issue by Michael1001** [hashrock/JPainter#1]
Hello!
I try to open an ".exr" file using OpenEXR class, what I could run because it has main method.
Could someone tell me please, if possible generally to be opened an EXR file using this application?

**Comment by Michael1001** [comment]
When I try to open an EXR file a get this exception
```
ex java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at imagez.image.ZImage.getLayer(ZImage.java:441)
	at imagez.io.OpenEXR$1.run(OpenEXR.java:430)
```

**Comment by hashrock** [comment]
This repository is currently not maintained. Also, the original version of ImageZ seems to have disappeared.

I have never used EXR file, so I don't know if this tool can handle common EXR files, but I recommend to use other popular EXR libraries.

**Comment by Michael1001** [comment]
Thank you hashrock for  your prompt response. 
I know about other EXR libraries, but them are written on for C++, and is not direct way of use a library concret for Java.
